load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "f1_lib",
    srcs = ["f1.java"],
    deps = [
        "@maven//:com_google_code_gson_gson",
    ],
    visibility = ["//visibility:public"],
)